In [2]:
import pandas as pd

In [3]:
raw_data=pd.read_csv("fake_real_job_postings_3000x25.csv")

In [4]:
data=pd.read_csv("fake_real_job_postings_3000x25.csv")

In [5]:
data.head()

,job_id,job_title,job_description,requirements,benefits,company_name,company_profile,industry,employment_type,location,...,application_deadline,contact_email,company_website,has_logo,num_open_positions,job_function,telecommuting,fraud_reason,text_length,is_fake
0,1,Software Engineer,We are looking for responsibilities fast-paced...,Candidates should have dynamic team skills fas...,We offer required skills fast-paced skills req...,Company_543,Our company growth fast-paced responsibilities...,Marketing,Contract,"Toronto, Canada",...,2024-09-16,hr312@company.com,https://www.company.com,0,3,Management,0,NaN,89,0
1,2,Content Writer,We are looking for required support experience...,Candidates should have required team fast-pace...,We offer fast-paced dynamic dynamic strategy g...,Company_192,Our company fast-paced opportunity innovation ...,Finance,Full-time,"Toronto, Canada",...,2024-10-18,hr127@company.com,https://www.company.com,0,10,Development,1,NaN,89,0
2,3,Customer Support Specialist,We are looking for dynamic required fast-paced...,Candidates should have preferred knowledge opp...,We offer skills experience required growth res...,NaN,We are global innovation growth skills knowled...,Healthcare,Internship,Remote,...,2024-01-13,job92@gmail.com,NaN,0,6,Support,0,Suspicious email,69,1
3,4,Data Analyst,We are looking for collaboration skills suppor...,Candidates should have innovation team require...,We offer strategy strategy dynamic support opp...,Company_95,Our company fast-paced support team strategy i...,Healthcare,Part-time,"Berlin, Germany",...,2024-02-09,hr366@company.com,https://www.company.com,1,4,Management,1,NaN,89,0
4,5,Graphic Designer,We are looking for team growth growth fast-pac...,Candidates should have experience preferred kn...,We offer opportunity skills responsibilities c...,NaN,We are global experience skills preferred fast...,Retail,Part-time,"London, UK",...,2024-08-26,job359@gmail.com,NaN,0,5,Management,0,No salary info,69,1

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   job_id                     3000 non-null   int64
 1   job_title                  3000 non-null   str
 2   job_description            3000 non-null   str
 3   requirements               3000 non-null   str
 4   benefits                   3000 non-null   str
 5   company_name               1528 non-null   str
 6   company_profile            3000 non-null   str
 7   industry                   3000 non-null   str
 8   employment_type            3000 non-null   str
 9   location                   3000 non-null   str
 10  salary_range               3000 non-null   str
 11  required_experience_years  3000 non-null   int64
 12  education_level            3000 non-null   str
 13  department                 3000 non-null   str
 14  posting_date               3000 non-null   str
 15  application_deadline       3000 non-null   str
 16  contact_email              3000 non-null   str
 17  company_website            1528 non-null   str
 18  has_logo                   3000 non-null   int64
 19  num_open_positions         3000 non-null   int64
 20  job_function               3000 non-null   str
 21  telecommuting              3000 non-null   int64
 22  fraud_reason               1472 non-null   str
 23  text_length                3000 non-null   int64
 24  is_fake                    3000 non-null   int64
dtypes: int64(7), str(18)
memory usage: 586.1 KB

In [7]:
data.isnull().sum()

job_id                          0
job_title                       0
job_description                 0
requirements                    0
benefits                        0
company_name                 1472
company_profile                 0
industry                        0
employment_type                 0
location                        0
salary_range                    0
required_experience_years       0
education_level                 0
department                      0
posting_date                    0
application_deadline            0
contact_email                   0
company_website              1472
has_logo                        0
num_open_positions              0
job_function                    0
telecommuting                   0
fraud_reason                 1528
text_length                     0
is_fake                         0
dtype: int64

In [8]:
(data.isnull().sum() / len(data)) * 100

job_id                        0.000000
job_title                     0.000000
job_description               0.000000
requirements                  0.000000
benefits                      0.000000
company_name                 49.066667
company_profile               0.000000
industry                      0.000000
employment_type               0.000000
location                      0.000000
salary_range                  0.000000
required_experience_years     0.000000
education_level               0.000000
department                    0.000000
posting_date                  0.000000
application_deadline          0.000000
contact_email                 0.000000
company_website              49.066667
has_logo                      0.000000
num_open_positions            0.000000
job_function                  0.000000
telecommuting                 0.000000
fraud_reason                 50.933333
text_length                   0.000000
is_fake                       0.000000
dtype: float64

In [9]:
data["company_name"]

0       Company_543
1       Company_192
2               NaN
3        Company_95
4               NaN
           ...
2995    Company_159
2996            NaN
2997            NaN
2998            NaN
2999    Company_354
Name: company_name, Length: 3000, dtype: str

In [10]:
data = data.drop(columns=[
    "job_id",
    "location",
    "application_deadline"
])

In [11]:
data.head()

,job_title,job_description,requirements,benefits,company_name,company_profile,industry,employment_type,salary_range,required_experience_years,...,posting_date,contact_email,company_website,has_logo,num_open_positions,job_function,telecommuting,fraud_reason,text_length,is_fake
0,Software Engineer,We are looking for responsibilities fast-paced...,Candidates should have dynamic team skills fas...,We offer required skills fast-paced skills req...,Company_543,Our company growth fast-paced responsibilities...,Marketing,Contract,$60k-$80k,8,...,2023-11-24,hr312@company.com,https://www.company.com,0,3,Management,0,NaN,89,0
1,Content Writer,We are looking for required support experience...,Candidates should have required team fast-pace...,We offer fast-paced dynamic dynamic strategy g...,Company_192,Our company fast-paced opportunity innovation ...,Finance,Full-time,$40k-$60k,10,...,2023-03-03,hr127@company.com,https://www.company.com,0,10,Development,1,NaN,89,0
2,Customer Support Specialist,We are looking for dynamic required fast-paced...,Candidates should have preferred knowledge opp...,We offer skills experience required growth res...,NaN,We are global innovation growth skills knowled...,Healthcare,Internship,$60k-$80k,3,...,2023-07-31,job92@gmail.com,NaN,0,6,Support,0,Suspicious email,69,1
3,Data Analyst,We are looking for collaboration skills suppor...,Candidates should have innovation team require...,We offer strategy strategy dynamic support opp...,Company_95,Our company fast-paced support team strategy i...,Healthcare,Part-time,Not Disclosed,10,...,2023-08-14,hr366@company.com,https://www.company.com,1,4,Management,1,NaN,89,0
4,Graphic Designer,We are looking for team growth growth fast-pac...,Candidates should have experience preferred kn...,We offer opportunity skills responsibilities c...,NaN,We are global experience skills preferred fast...,Retail,Part-time,$60k-$80k,7,...,2023-04-22,job359@gmail.com,NaN,0,5,Management,0,No salary info,69,1

In [12]:
missing = data.isnull().sum().sort_values(ascending=False)
missing

fraud_reason                 1528
company_name                 1472
company_website              1472
requirements                    0
job_description                 0
job_title                       0
company_profile                 0
benefits                        0
industry                        0
employment_type                 0
education_level                 0
department                      0
salary_range                    0
required_experience_years       0
contact_email                   0
posting_date                    0
num_open_positions              0
has_logo                        0
job_function                    0
telecommuting                   0
text_length                     0
is_fake                         0
dtype: int64

In [13]:
missing_summary = pd.DataFrame({
    "Missing Values": data.isnull().sum(),
    "Percentage": (data.isnull().sum() / len(data)) * 100
})

missing_summary.sort_values(by="Percentage", ascending=False)

                           Missing Values  Percentage
fraud_reason                         1528   50.933333
company_name                         1472   49.066667
company_website                      1472   49.066667
requirements                            0    0.000000
job_description                         0    0.000000
job_title                               0    0.000000
company_profile                         0    0.000000
benefits                                0    0.000000
industry                                0    0.000000
employment_type                         0    0.000000
education_level                         0    0.000000
department                              0    0.000000
salary_range                            0    0.000000
required_experience_years               0    0.000000
contact_email                           0    0.000000
posting_date                            0    0.000000
num_open_positions                      0    0.000000
has_logo                                0    0.000000
job_function                            0    0.000000
telecommuting                           0    0.000000
text_length                             0    0.000000
is_fake                                 0    0.000000

In [14]:
data.head(20)

,job_title,job_description,requirements,benefits,company_name,company_profile,industry,employment_type,salary_range,required_experience_years,...,posting_date,contact_email,company_website,has_logo,num_open_positions,job_function,telecommuting,fraud_reason,text_length,is_fake
0,Software Engineer,We are looking for responsibilities fast-paced...,Candidates should have dynamic team skills fas...,We offer required skills fast-paced skills req...,Company_543,Our company growth fast-paced responsibilities...,Marketing,Contract,$60k-$80k,8,...,2023-11-24,hr312@company.com,https://www.company.com,0,3,Management,0,NaN,89,0
1,Content Writer,We are looking for required support experience...,Candidates should have required team fast-pace...,We offer fast-paced dynamic dynamic strategy g...,Company_192,Our company fast-paced opportunity innovation ...,Finance,Full-time,$40k-$60k,10,...,2023-03-03,hr127@company.com,https://www.company.com,0,10,Development,1,NaN,89,0
2,Customer Support Specialist,We are looking for dynamic required fast-paced...,Candidates should have preferred knowledge opp...,We offer skills experience required growth res...,NaN,We are global innovation growth skills knowled...,Healthcare,Internship,$60k-$80k,3,...,2023-07-31,job92@gmail.com,NaN,0,6,Support,0,Suspicious email,69,1
3,Data Analyst,We are looking for collaboration skills suppor...,Candidates should have innovation team require...,We offer strategy strategy dynamic support opp...,Company_95,Our company fast-paced support team strategy i...,Healthcare,Part-time,Not Disclosed,10,...,2023-08-14,hr366@company.com,https://www.company.com,1,4,Management,1,NaN,89,0
4,Graphic Designer,We are looking for team growth growth fast-pac...,Candidates should have experience preferred kn...,We offer opportunity skills responsibilities c...,NaN,We are global experience skills preferred fast...,Retail,Part-time,$60k-$80k,7,...,2023-04-22,job359@gmail.com,NaN,0,5,Management,0,No salary info,69,1
5,Marketing Manager,We are looking for knowledge development exper...,Candidates should have collaboration required ...,We offer knowledge fast-paced collaboration fa...,Company_473,Our company development dynamic required devel...,Education,Contract,$40k-$60k,4,...,2023-02-03,hr252@company.com,https://www.company.com,0,10,Development,0,NaN,89,0
6,Content Writer,We are looking for knowledge team fast-paced d...,Candidates should have growth responsibilities...,We offer responsibilities skills opportunity s...,Company_215,Our company opportunity required innovation su...,IT,Internship,$60k-$80k,4,...,2023-07-28,hr116@company.com,https://www.company.com,0,8,Development,0,NaN,89,0
7,Customer Support Specialist,We are looking for responsibilities innovation...,Candidates should have strategy support prefer...,We offer strategy experience growth innovation...,NaN,We are global skills team fast-paced knowledge...,Finance,Contract,$40k-$60k,5,...,2023-07-03,job221@gmail.com,NaN,0,3,Analysis,1,No salary info,69,1
8,Marketing Manager,We are looking for opportunity team collaborat...,Candidates should have preferred fast-paced dy...,We offer required development strategy team gr...,Company_537,Our company collaboration preferred developmen...,Retail,Temporary,$40k-$60k,5,...,2023-08-16,hr438@company.com,https://www.company.com,1,2,Management,1,NaN,89,0
9,Business Analyst,We are looking for responsibilities dynamic de...,Candidates should have strategy preferred deve...,We offer knowledge strategy innovation develop...,Company_641,Our company innovation required responsibiliti...,Healthcare,Internship,$40k-$60k,4,...,2023-10-15,hr315@company.com,https://www.company.com,0,10,Management,0,NaN,89,0
10,Customer Support Specialist,We are looking for knowledge required preferre...,Candidates should have knowledge skills fast-p...,We offer innovation experience strategy team r...,Company_742,Our company team innovation development fast-p...,Retail,Internship,$80k-$100k,10,...,2023-08-14,hr241@company.com,https://www.company.com,1,5,Management,0,NaN,89,0
11,Graphic Designer,We are looking for team knowledge strategy str...,Candidates should have development required te...,We offer team growth preferred knowledge colla...,NaN,We are global preferred knowledge opportunity ...,IT,Contract,$40k-$60k,10,...,2023-03-09,job193@gmail.com,NaN,0,3,Analysis,0,No salary info,69,1
12,HR Coordinator,We are looking for skills innovation preferred...,Candidates should have skills collaboration pr...,We offer growth innovation development knowled...,Company_1056,Our company fast-paced growth knowledge innova...,Marketing,Part-time,Not Disclosed,10,...,2023-02-02,hr19@company.com,https://www.company.com,1,4,Development,0,NaN,89,0
13,Product Manager,We are looking for knowledge collaboration sup...,Candidates should have strategy skills preferr...,We offer strategy team growth preferred collab...,Company_534,Our company strategy dynamic knowledge support...,Retail,Part-time,$40k-$60k,1,...,2023-09-03,hr211@company.com,https://www.company.com,1,10,Development,0,NaN,89,0
14,Data Analyst,We are looking for strategy strategy preferred...,Candidates should have responsibilities growth...,We offer skills opportunity strategy innovatio...,NaN,We are global development required fast-paced ...,IT,Contract,Not Disclosed,3,...,2023-10-23,job98@gmail.com,NaN,0,3,Support,1,Suspicious email,69,1
15,HR Coordinator,We are looking for experience team collaborati...,Candidates should have preferred skills collab...,We offer required support strategy growth grow...,NaN,We are global preferred required development i...,Retail,Temporary,Not Disclosed,2,...,2023-10-21,job57@gmail.com,NaN,0,4,Development,1,Suspicious email,69,1
16,Marketing Manager,We are looking for innovation dynamic innovati...,Candidates should have knowledge fast-paced kn...,We offer dynamic responsibilities responsibili...,NaN,We are global development growth experience op...,Healthcare,Full-time,$60k-$80k,8,...,2023-08-02,job479@gmail.com,NaN,0,1,Support,1,Unverified company,69,1
17,Software Engineer,We are looking for experience knowledge develo...,Candidates should have dynamic opportunity col...,We offer skills development strategy knowledge...,NaN,We are global strategy preferred innovation su...,Retail,Full-time,$60k-$80k,9,...,2023-06-17,job227@gmail.com,NaN,0,2,Analysis,1,Unverified company,69,1
18,Software Engineer,We are looking for strategy growth innovation ...,Candidates should have skills knowledge innova...,We offer fast-paced fast-paced strategy prefer...,NaN,We are global skills strategy skills fast-pace...,Finance,Internship,$60k-$80k,9,...,2023-11-03,job420@gmail.com,NaN,0,6,Analysis,1,Unverified company,69,1
19,Business Analyst,We are looking for knowledge responsibilities ...,Candidates should have team dynamic dynamic su...,We offer strategy development support required...,Company_313,Our company dynamic required fast-paced collab...,Healthcare,Full-time,Not Disclosed,10,...,2023-01-04,hr283@company.com,https://www.company.com,1,1,Development,1,NaN,89,0

In [15]:
pd.crosstab(
    data["company_name"].isnull(),
    data["is_fake"]
)

is_fake          0     1
company_name
False         1528     0
True             0  1472

In [16]:
pd.crosstab(
    data["company_website"].isnull(),
    data["is_fake"]
)

is_fake             0     1
company_website
False            1528     0
True                0  1472

In [17]:
pd.crosstab(
    data["has_logo"],
    data["is_fake"]
)

is_fake     0     1
has_logo
0         790  1472
1         738     0

In [18]:
data = data.drop(columns=[
    "fraud_reason",
    "company_name",
    "company_website"
])

In [19]:
data.head(10)

,job_title,job_description,requirements,benefits,company_profile,industry,employment_type,salary_range,required_experience_years,education_level,department,posting_date,contact_email,has_logo,num_open_positions,job_function,telecommuting,text_length,is_fake
0,Software Engineer,We are looking for responsibilities fast-paced...,Candidates should have dynamic team skills fas...,We offer required skills fast-paced skills req...,Our company growth fast-paced responsibilities...,Marketing,Contract,$60k-$80k,8,High School,Sales,2023-11-24,hr312@company.com,0,3,Management,0,89,0
1,Content Writer,We are looking for required support experience...,Candidates should have required team fast-pace...,We offer fast-paced dynamic dynamic strategy g...,Our company fast-paced opportunity innovation ...,Finance,Full-time,$40k-$60k,10,Bachelor,HR,2023-03-03,hr127@company.com,0,10,Development,1,89,0
2,Customer Support Specialist,We are looking for dynamic required fast-paced...,Candidates should have preferred knowledge opp...,We offer skills experience required growth res...,We are global innovation growth skills knowled...,Healthcare,Internship,$60k-$80k,3,Bachelor,Marketing,2023-07-31,job92@gmail.com,0,6,Support,0,69,1
3,Data Analyst,We are looking for collaboration skills suppor...,Candidates should have innovation team require...,We offer strategy strategy dynamic support opp...,Our company fast-paced support team strategy i...,Healthcare,Part-time,Not Disclosed,10,Bachelor,Sales,2023-08-14,hr366@company.com,1,4,Management,1,89,0
4,Graphic Designer,We are looking for team growth growth fast-pac...,Candidates should have experience preferred kn...,We offer opportunity skills responsibilities c...,We are global experience skills preferred fast...,Retail,Part-time,$60k-$80k,7,High School,Design,2023-04-22,job359@gmail.com,0,5,Management,0,69,1
5,Marketing Manager,We are looking for knowledge development exper...,Candidates should have collaboration required ...,We offer knowledge fast-paced collaboration fa...,Our company development dynamic required devel...,Education,Contract,$40k-$60k,4,PhD,Engineering,2023-02-03,hr252@company.com,0,10,Development,0,89,0
6,Content Writer,We are looking for knowledge team fast-paced d...,Candidates should have growth responsibilities...,We offer responsibilities skills opportunity s...,Our company opportunity required innovation su...,IT,Internship,$60k-$80k,4,High School,Design,2023-07-28,hr116@company.com,0,8,Development,0,89,0
7,Customer Support Specialist,We are looking for responsibilities innovation...,Candidates should have strategy support prefer...,We offer strategy experience growth innovation...,We are global skills team fast-paced knowledge...,Finance,Contract,$40k-$60k,5,High School,Sales,2023-07-03,job221@gmail.com,0,3,Analysis,1,69,1
8,Marketing Manager,We are looking for opportunity team collaborat...,Candidates should have preferred fast-paced dy...,We offer required development strategy team gr...,Our company collaboration preferred developmen...,Retail,Temporary,$40k-$60k,5,Bachelor,HR,2023-08-16,hr438@company.com,1,2,Management,1,89,0
9,Business Analyst,We are looking for responsibilities dynamic de...,Candidates should have strategy preferred deve...,We offer knowledge strategy innovation develop...,Our company innovation required responsibiliti...,Healthcare,Internship,$40k-$60k,4,Bachelor,HR,2023-10-15,hr315@company.com,0,10,Management,0,89,0

In [20]:
data.duplicated().sum()

np.int64(0)

In [21]:
data.select_dtypes(include="string").columns

Index(['job_title', 'job_description', 'requirements', 'benefits',
       'company_profile', 'industry', 'employment_type', 'salary_range',
       'education_level', 'department', 'posting_date', 'contact_email',
       'job_function'],
      dtype='str')

In [22]:
data["employment_type"].unique()

<StringArray>
['Contract', 'Full-time', 'Internship', 'Part-time', 'Temporary']
Length: 5, dtype: str

In [23]:
data['job_title'].unique()

<StringArray>
[          'Software Engineer',              'Content Writer',
 'Customer Support Specialist',                'Data Analyst',
            'Graphic Designer',           'Marketing Manager',
            'Business Analyst',              'HR Coordinator',
             'Product Manager',             'Sales Executive']
Length: 10, dtype: str

In [24]:
data["application_deadline"] = raw_data["application_deadline"]

In [25]:
data.head(10)

,job_title,job_description,requirements,benefits,company_profile,industry,employment_type,salary_range,required_experience_years,education_level,department,posting_date,contact_email,has_logo,num_open_positions,job_function,telecommuting,text_length,is_fake,application_deadline
0,Software Engineer,We are looking for responsibilities fast-paced...,Candidates should have dynamic team skills fas...,We offer required skills fast-paced skills req...,Our company growth fast-paced responsibilities...,Marketing,Contract,$60k-$80k,8,High School,Sales,2023-11-24,hr312@company.com,0,3,Management,0,89,0,2024-09-16
1,Content Writer,We are looking for required support experience...,Candidates should have required team fast-pace...,We offer fast-paced dynamic dynamic strategy g...,Our company fast-paced opportunity innovation ...,Finance,Full-time,$40k-$60k,10,Bachelor,HR,2023-03-03,hr127@company.com,0,10,Development,1,89,0,2024-10-18
2,Customer Support Specialist,We are looking for dynamic required fast-paced...,Candidates should have preferred knowledge opp...,We offer skills experience required growth res...,We are global innovation growth skills knowled...,Healthcare,Internship,$60k-$80k,3,Bachelor,Marketing,2023-07-31,job92@gmail.com,0,6,Support,0,69,1,2024-01-13
3,Data Analyst,We are looking for collaboration skills suppor...,Candidates should have innovation team require...,We offer strategy strategy dynamic support opp...,Our company fast-paced support team strategy i...,Healthcare,Part-time,Not Disclosed,10,Bachelor,Sales,2023-08-14,hr366@company.com,1,4,Management,1,89,0,2024-02-09
4,Graphic Designer,We are looking for team growth growth fast-pac...,Candidates should have experience preferred kn...,We offer opportunity skills responsibilities c...,We are global experience skills preferred fast...,Retail,Part-time,$60k-$80k,7,High School,Design,2023-04-22,job359@gmail.com,0,5,Management,0,69,1,2024-08-26
5,Marketing Manager,We are looking for knowledge development exper...,Candidates should have collaboration required ...,We offer knowledge fast-paced collaboration fa...,Our company development dynamic required devel...,Education,Contract,$40k-$60k,4,PhD,Engineering,2023-02-03,hr252@company.com,0,10,Development,0,89,0,2024-07-24
6,Content Writer,We are looking for knowledge team fast-paced d...,Candidates should have growth responsibilities...,We offer responsibilities skills opportunity s...,Our company opportunity required innovation su...,IT,Internship,$60k-$80k,4,High School,Design,2023-07-28,hr116@company.com,0,8,Development,0,89,0,2024-02-17
7,Customer Support Specialist,We are looking for responsibilities innovation...,Candidates should have strategy support prefer...,We offer strategy experience growth innovation...,We are global skills team fast-paced knowledge...,Finance,Contract,$40k-$60k,5,High School,Sales,2023-07-03,job221@gmail.com,0,3,Analysis,1,69,1,2024-07-10
8,Marketing Manager,We are looking for opportunity team collaborat...,Candidates should have preferred fast-paced dy...,We offer required development strategy team gr...,Our company collaboration preferred developmen...,Retail,Temporary,$40k-$60k,5,Bachelor,HR,2023-08-16,hr438@company.com,1,2,Management,1,89,0,2024-04-30
9,Business Analyst,We are looking for responsibilities dynamic de...,Candidates should have strategy preferred deve...,We offer knowledge strategy innovation develop...,Our company innovation required responsibiliti...,Healthcare,Internship,$40k-$60k,4,Bachelor,HR,2023-10-15,hr315@company.com,0,10,Management,0,89,0,2024-11-14

In [29]:
categorical_cols = data.select_dtypes(include="str").columns

print(categorical_cols)

Index(['job_title', 'job_description', 'requirements', 'benefits',
       'company_profile', 'industry', 'employment_type', 'salary_range',
       'education_level', 'department', 'posting_date', 'contact_email',
       'job_function', 'application_deadline'],
      dtype='str')

In [31]:
data["employment_type"].value_counts(dropna=False)

employment_type
Part-time     615
Full-time     614
Internship    605
Contract      598
Temporary     568
Name: count, dtype: int64

In [33]:
data["education_level"].value_counts(dropna=False)

education_level
Bachelor       793
Master         752
PhD            737
High School    718
Name: count, dtype: int64

In [34]:
data["posting_date"] = pd.to_datetime(data["posting_date"])
data["application_deadline"] = pd.to_datetime(data["application_deadline"])

In [35]:
data["posting_date"].dt.year
data["posting_date"].dt.month
data["posting_date"].dt.day_name()

0         Friday
1         Friday
2         Monday
3         Monday
4       Saturday
          ...
2995      Sunday
2996      Sunday
2997      Sunday
2998     Tuesday
2999     Tuesday
Name: posting_date, Length: 3000, dtype: str

In [36]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   job_title                  3000 non-null   str
 1   job_description            3000 non-null   str
 2   requirements               3000 non-null   str
 3   benefits                   3000 non-null   str
 4   company_profile            3000 non-null   str
 5   industry                   3000 non-null   str
 6   employment_type            3000 non-null   str
 7   salary_range               3000 non-null   str
 8   required_experience_years  3000 non-null   int64
 9   education_level            3000 non-null   str
 10  department                 3000 non-null   str
 11  posting_date               3000 non-null   datetime64[us]
 12  contact_email              3000 non-null   str
 13  has_logo                   3000 non-null   int64
 14  num_open_positions         3000 non-null   int64
 15  job_function               3000 non-null   str
 16  telecommuting              3000 non-null   int64
 17  text_length                3000 non-null   int64
 18  is_fake                    3000 non-null   int64
 19  application_deadline       3000 non-null   datetime64[us]
dtypes: datetime64[us](2), int64(6), str(12)
memory usage: 468.9 KB

In [37]:
(data["application_deadline"] < data["posting_date"]).sum()

np.int64(0)

In [38]:
data.to_csv("/home/abhinav/Desktop/Fk_Jb_Detection project/CleanData.csv")